# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Desafio_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Desafio_iOS

   pod 'Alamofire', '~> 5.2'

  target 'Desafio_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Desafio_iOSUITests' do
    # Pods for testing
  end

end
