# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'NASA' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NASA

  target 'NASATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NASAUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.15.7'

end
